name: 'Pull Request Ticket Check Action'
description: 'Verify that pull request titles start with a ticket ID'
author: 'Neo Financial Engineering'

inputs:
  titleFormat:
    description: "The intended format the title should be set to if it doesn't match the regular expression. Available variables are `%ticketPrefix%`, `%ticketNumber%`, and `%title%`"
    default: '[%ticketPrefix% %ticketNumber%]: %title%'
    required: true

  titleRegex:
    description: 'The regular expression used to search the title for the intended format'
    default: '^\[(?<ticketPrefix>bugfix|feat|hotfix|release|wip) (?<ticketNumber>(\d{3,},?\s*)+)\]'
    required: true

  titleRegexFlags:
    description: 'The regular expression flags applied to the title regular expression'
    default: 'gi'
    required: true

  branchRegex:
    description: 'The regular expression used to search the branch for the intended format'
    default: '^(?<ticketPrefix>bugfix|feat|hotfix|release|wip)\/(?<ticketNumber>(-?\d{3,})+)'
    required: true

  branchRegexFlags:
    description: 'The regular expression flags applied to the branch regular expression'
    default: 'gi'
    required: true

  exemptUsers:
    description: 'User(s) who will be exempt from the ticket check rules. Particularly useful for automated/bot PRs. 
    Comma separated.'
    default: 'dependabot'
    required: false

  quiet:
    description: 'Suppress comment on successful PR title update'
    default: 'true'
    required: false

  token:
    description: 'GitHub authentication token'
    required: true

  ticketLink:
    description: 'Ticket URL with `%ticketNumber%` and `%ticketPrefix%` placeholders'
    required: false

runs:
  using: 'node12'
  main: 'build/index.js'

branding:
  icon: 'git-pull-request'
  color: 'blue'
